### ISSUE TITLE
Nothing gets created and Java files don't show in File Finder window

### ISSUE THREAD

**Issue by StanFromTraction** [OH318/J-Diagram#6]

**Comment by abulka** [comment]
Doesn't work. Am on a Mac.

**Comment by jiniljeil** [comment]
The problem that did not run on Windows has been fixed. Also, Mac too.

**Comment by abulka** [comment]
Has this fix been published?  Latest version as of today `v0.0.9` still generates nothing on my Mac.
```
More Info
Published
5/28/2022, 15:03:04
Last released
6/25/2023, 03:55:15
Last updated
6/26/2023, 09:31:47
Identifier
oh318.j-diagram
```
P.S. The changelog in the extension is not being maintained - that would be good place to note any fixes IMO.

**Comment by jiniljeil** [comment]
Hello, I am Kim Jin-il in charge of J-diagram maintenance.

Sorry for the late reply.

Could you send me the Draw.io file for testing in a different environment?

-----Original Message-----

**Comment by abulka** [comment]
Where is the generated draw.io diagram file supposed to be? As I said in the issue this extension "generates nothing on my Mac."

**Comment by jiniljeil** [comment]
The draw.io file is generated in the directory path placed by user.

The problem can taken place when the access modifer of member variable is default. Because "org.jboss.forge.roaster.Roaster" only support private, protected, and public. 
In addtion, the java interface source code does not support. we are going to update the interface function.

We could not consider the all cases when developing the j-diagram. If you need the other function, tell me about it. I going to update the j-diagram.  


-----Original Message-----

**Comment by abulka** [comment]
I finally got some ouput! The extension's "Current directory" output option is misleading and probably causing most users of this extension to think it is broken.

1. I just installed the extension fresh.
2. I created a simple java file
```java
package com.aaa.bbb;

public class Simple {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
    
    // method that adds two numbers
    public static int add(int a, int b) {
        return a + b;
    }
}
```
3. I select the command "J Diagram: Convert java sources to draw.io file"
4. I select "open file finder" and select the `Simple.java` file
5. I select output to "Current directory"
6. I look for the draw.io file in the same directory as the`Simple.java` file but cannot find it.

Update: turns out that "Current directory" output option puts the file in 
`target/classes/com/aaa/bbb/j-diagram.drawio` where nobody will find it.

The better option to use when "Open File Finder" when asked "Choose where to where to make draw.io" diagram and selecting a better location within your project.

P.S. Also nothing is generated when the draw.io file already exists.
